import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#131313",
        surface: "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "surface-card": "#1E1E1E",
        "surface-card-hover": "#252525",
        "surface-card-elevated": "#2A2A2A",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#c1c6d6",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        outline: "#8b909f",
        "outline-variant": "#414754",
        "surface-tint": "#adc7ff",
        primary: "#adc7ff",
        "on-primary": "#002e68",
        "primary-container": "#1a73e8",
        "on-primary-container": "#ffffff",
        "inverse-primary": "#005bc0",
        secondary: "#dab9ff",
        "on-secondary": "#460283",
        "secondary-container": "#602b9d",
        "on-secondary-container": "#cfa7ff",
        tertiary: "#ffb691",
        "on-tertiary": "#552100",
        "tertiary-container": "#c55500",
        "on-tertiary-container": "#0e0200",
        "border-subtle": "#2E2E2E",
        "border-strong": "#3D3D3D",
        "text-primary": "#FFFFFF",
        "text-secondary": "#B3B3B3",
        "text-muted": "#757575",
        "status-success": "#4CAF50",
        "status-warning": "#FFC107",
        "status-error": "#F44336",
        "status-info": "#03A9F4",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        gutter: "1rem",
        "gutter-desktop": "1.5rem",
        margin: "1rem",
        "margin-tablet": "1.5rem",
        "margin-desktop": "2rem",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
